# Generated by Django 5.0.1 on 2024-02-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0002_alter_instructor_d_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="instructor_d",
            managers=[],
        ),
    ]
