# Generated by Django 5.0.1 on 2024-02-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0003_alter_instructor_d_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor_d",
            name="password",
            field=models.CharField(max_length=120),
        ),
    ]
