# Generated by Django 5.0.1 on 2024-02-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0004_alter_instructor_d_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor_d",
            name="phone",
            field=models.CharField(max_length=12),
        ),
    ]
