# Generated by Django 5.0.1 on 2024-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0005_alter_instructor_d_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor_d",
            name="about",
            field=models.CharField(
                default="I’ve found a way to get paid for my favorite hobby, and do so while following my dream of traveling the world.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="instructor_d",
            name="certificate",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/cerificate/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="instructor_d",
            name="education",
            field=models.CharField(default="Bachelor of Technology", max_length=500),
        ),
        migrations.AddField(
            model_name="instructor_d",
            name="experience",
            field=models.IntegerField(default="0", max_length=2),
        ),
        migrations.AddField(
            model_name="instructor_d",
            name="location",
            field=models.CharField(default="location", max_length=50),
        ),
        migrations.AddField(
            model_name="instructor_d",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/pic/%Y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="instructor_d",
            name="skills",
            field=models.CharField(default="data science", max_length=500),
        ),
    ]
