# Generated by Django 5.0.1 on 2024-03-01 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0006_instructor_d_about_instructor_d_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor_d",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
