# Generated by Django 5.0.1 on 2024-03-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0007_alter_instructor_d_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor_d",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
