# Generated by Django 3.2.25 on 2024-03-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_rename_full_name_instructor_d_collegename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor_d',
            name='address',
            field=models.TextField(blank=True, default='DEFAULT VALUE', null=True),
        ),
        migrations.AddField(
            model_name='instructor_d',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic'),
        ),
    ]
