# Generated by Django 3.2.25 on 2024-03-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_auto_20240308_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor_d',
            name='aboutcollege',
            field=models.TextField(blank=True, default='DEFAULT VALUE', null=True),
        ),
    ]
